vim.g.mapleader = " "
vim.scriptencoding = "utf-8"
vim.g.snacks_animate = true

local opt = vim.opt

opt.number = true
opt.cursorline = true
opt.termguicolors = true
opt.relativenumber = true
opt.splitbelow = true
opt.splitright = true
opt.clipboard = "unnamedplus"
opt.encoding = "utf-8"
opt.fileencoding = "utf-8"
opt.expandtab = true
opt.hlsearch = false
opt.ignorecase = true
opt.smartcase = true
opt.ttyfast = true
opt.showmatch = true
opt.expandtab = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.autoindent = false
opt.linebreak = true
opt.mouse = "a"
opt.showmode = false
opt.smartindent = true
opt.smoothscroll = true
opt.undolevels = 10000
